name: pr

on:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
      -
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      -
        name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      -
        name: go fmt
        run: |
          go fmt ./...
          git diff --exit-code
      -
        name: go test
        run: |
          go test ./...
